# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install system dependencies for Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-qt pytest-cov
        if [ -f reqs.txt ]; then python -m pip install -r reqs.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # Run tests with virtual display for Qt GUI testing
        xvfb-run -a pytest --cov=src --cov-report=xml --cov-report=term-missing -v
      env:
        QT_QPA_PLATFORM: offscreen
        QT_LOGGING_RULES: "*.debug=false"
        DISPLAY: :99
